### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by aubymori** [NetworkNeighborhood/Nara#1]
Here's a list of things that need to be done for Nara, in no particular order:

- Restore native Win32 control styles:
  - [ ] Basic/classic titlebar and caption buttons
  - [x] Focus outlines
  - [ ] Scrollbars
  - [x] Radio buttons
  - [x] Checkboxes
  - [x] Spinner buttons
  - [ ] Menulist arrows
  - Tree/list view parts
    - [ ] List items
    - [ ] Tree views
    - [ ] Tree twisties
    - [ ] Tree items
  - [ ] DWM (glass) titlebar and caption buttons
  - [ ] Toolboxes
  - [ ] Toolbars
  - [ ] Status bars
  - [ ] Menus
- Restore/implement nonstandard CSS properties which are convenient for the UI Nara is trying to achieve
  - [x] `-moz-outline-radius`
  - [x] `-moz-image-region`
- Fix issues with WebRender\*
  - [ ] DWM caption button mask breaks unless software renderer is used
  - [ ] DWM caption button mask cannot be rounded
  - [ ] Tree text rendering doesn't respect the user having ClearType disabled
- Port XBL-based controls that were removed entirely to custom elements
  - [ ] Preferences window controls (e.g. `prefpane`)
  - [ ] Status bar controls
- Port XUL overlays? Seem to be used by `prefpane` control and also seem to be gone. Will not add this as a task for now. We'll see when the time comes.

\*There are two ways to go about this:
1. Fix the issues in WebRender itself (probably the preferred option)
2. Restore the old "Layers" rendering system (will this impact performance?)

**Comment by VORAPIS** [comment]
hi :3
